# 2. H2
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# 3. Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
# 4. Dummy
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:db/data.sql
# 6. Query Format
spring.jpa.properties.hibernate.format_sql=true
# 7. OpenInView
spring.jpa.open-in-view=false
# 8. Logging
logging.level.org.hibernate.orm.jdbc.bind=INFO
logging.level.org.example.springv3=DEBUG
logging.level.org.springframework.security=DEBUG
# 9. FailOneEmpty
spring.jackson.serialization.fail-on-empty-beans=false

# 10. JWT
jwt.secret=homepage-local-test-jwt-secret-for-hs512-that-is-longer-than-sixty-four-bytes
